Initial raspberry component
kulturkrock/screencrash-components pull request #115
Opened 2023-01-17 19:19 UTC by AntonNeld

2023-01-24 15:12 UTC, mzlarsson requested changes
There are a lot of similarities between the previous component. Maybe it is not for this time, but for the future we should try to gather these common functionalities in one place and then reuse from there. That would make components much smaller, allowing them to focus more on their business logic.

2023-01-24 15:12 UTC, mzlarsson commented on raspberry/src/coreconnection.py
> +            "component": "audio",
Fix component name here

2023-02-07 19:59 UTC, AntonNeld commented
> There are a lot of similarities between this and the previous components. Maybe it is not for this time, but for the future we should try to gather these common functionalities in one place and then reuse from there. That would make components much smaller, allowing them to focus more on their business logic.

Makes sense, I agree

2023-02-07 19:59 UTC, AntonNeld commented on raspberry/src/coreconnection.py
> +            "component": "audio",
Done

2023-02-07 20:12 UTC, AntonNeld commented
Made one more commit after addressing the comment, since it rounded out the PR nicely. But that was the last one (unless you have more comments)

2023-03-01 17:12 UTC, mzlarsson approved these changes

2023-03-01 17:12 UTC, mzlarsson commented on ledController/src/commandhandler.py
> +        return {"client": "ledController"}
If you change to snake case in the other PR, do so here as well. If not, ignore this comment.

2023-03-08 20:09 UTC, merged